# -*- coding: UTF-8 -*-


# This file was *autogenerated* from the file pythontex-files-practica01/sage_default_default.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_7 = Integer(7); _sage_const_26 = Integer(26); _sage_const_14 = Integer(14); _sage_const_17 = Integer(17); _sage_const_8 = Integer(8)


import os
import sys
import codecs

if '--interactive' not in sys.argv[_sage_const_1 :]:
    if sys.version_info[_sage_const_0 ] == _sage_const_2 :
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr, 'strict')
    else:
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer, 'strict')

if '/usr/share/texlive/texmf-dist/scripts/pythontex' and '/usr/share/texlive/texmf-dist/scripts/pythontex' not in sys.path:
    sys.path.append('/usr/share/texlive/texmf-dist/scripts/pythontex')
from pythontex_utils import PythonTeXUtils
pytex = PythonTeXUtils()

pytex.docdir = os.getcwd()
if os.path.isdir('.'):
    os.chdir('.')
    if os.getcwd() not in sys.path:
        sys.path.append(os.getcwd())
else:
    if len(sys.argv) < _sage_const_2  or sys.argv[_sage_const_1 ] != '--manual':
        sys.exit('Cannot find directory .')
if pytex.docdir not in sys.path:
    sys.path.append(pytex.docdir)

pytex.formatter = latex


pytex.id = 'sage_default_default'
pytex.family = 'sage'
pytex.session = 'default'
pytex.restart = 'default'

pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '0'
pytex.line = '33'

print('=>PYTHONTEX:STDOUT#0#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#0#block#\n')
pytex.before()
A = matrix(QQ, [ [_sage_const_1 , _sage_const_1 /_sage_const_2 , -_sage_const_1 ], [_sage_const_2 , _sage_const_0 , _sage_const_1 /_sage_const_3 ] ])
B = matrix(QQ, [ [-_sage_const_1 , _sage_const_2 , _sage_const_0 ], [_sage_const_1 /_sage_const_2 , _sage_const_0 , -_sage_const_1 /_sage_const_3 ], [_sage_const_2 , _sage_const_0 , -_sage_const_1 ] ])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '1'
pytex.line = '37'

print('=>PYTHONTEX:STDOUT#1#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#1#i#\n')
pytex.before()
print(pytex.formatter(A*B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '2'
pytex.line = '38'

print('=>PYTHONTEX:STDOUT#2#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#2#i#\n')
pytex.before()
print(pytex.formatter(A*B.T))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '3'
pytex.line = '57'

print('=>PYTHONTEX:STDOUT#3#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#3#block#\n')
pytex.before()
A = matrix(QQ,[[_sage_const_1 ,_sage_const_1 /_sage_const_2 ,_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_2 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,-_sage_const_1 ,_sage_const_0 ]])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '4'
pytex.line = '59'

print('=>PYTHONTEX:STDOUT#4#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#4#i#\n')
pytex.before()
print(pytex.formatter(A))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '5'
pytex.line = '98'

print('=>PYTHONTEX:STDOUT#5#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#5#block#\n')
pytex.before()
A = matrix(QQ, [[_sage_const_1 ,_sage_const_1 /_sage_const_2 ,_sage_const_0 ,_sage_const_2 ,_sage_const_1 ,_sage_const_2 ], [_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,_sage_const_3 ,-_sage_const_1 ,_sage_const_0 ]])
A.subdivide([], _sage_const_4 )
A1 = A.subdivision(_sage_const_0 , _sage_const_0 )
A2 = A.subdivision(_sage_const_0 , _sage_const_1 )
B = matrix(QQ, _sage_const_2 , _sage_const_4 )
B[_sage_const_0 ,_sage_const_1 ] = _sage_const_1 
B[_sage_const_1 ,_sage_const_3 ] = _sage_const_1 
P = QQ['alpha0, alpha1, beta0, beta1']; (alpha0, alpha1, beta0, beta1,) = P._first_ngens(4)
B2 = matrix(P, [ [alpha0, beta0], [alpha1, beta1] ])
M = block_matrix([ [A1, A2], [B, B2] ])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '6'
pytex.line = '111'

print('=>PYTHONTEX:STDOUT#6#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#6#i#\n')
pytex.before()
print(pytex.formatter(A1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '7'
pytex.line = '111'

print('=>PYTHONTEX:STDOUT#7#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#7#i#\n')
pytex.before()
print(pytex.formatter(A2))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '8'
pytex.line = '111'

print('=>PYTHONTEX:STDOUT#8#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#8#i#\n')
pytex.before()
print(pytex.formatter(B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '9'
pytex.line = '111'

print('=>PYTHONTEX:STDOUT#9#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#9#i#\n')
pytex.before()
print(pytex.formatter(B2))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '10'
pytex.line = '113'

print('=>PYTHONTEX:STDOUT#10#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#10#i#\n')
pytex.before()
print(pytex.formatter(M))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '11'
pytex.line = '139'

print('=>PYTHONTEX:STDOUT#11#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#11#block#\n')
pytex.before()
A = matrix(QQ, [[_sage_const_5 , _sage_const_4 , -_sage_const_3 , _sage_const_1 ], [_sage_const_10 , _sage_const_7 , -_sage_const_1 , _sage_const_0 ], [_sage_const_26 , _sage_const_14 , _sage_const_17 , -_sage_const_8 ], [_sage_const_1 , _sage_const_3 , -_sage_const_10 , _sage_const_4 ]])
A1 = block_matrix([[A, _sage_const_1 ]])
R = A1.echelon_form()
P = R.subdivision(_sage_const_0 , _sage_const_1 )
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '12'
pytex.line = '145'

print('=>PYTHONTEX:STDOUT#12#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#12#i#\n')
pytex.before()
print(pytex.formatter(A))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '13'
pytex.line = '146'

print('=>PYTHONTEX:STDOUT#13#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#13#i#\n')
pytex.before()
print(pytex.formatter(R))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '14'
pytex.line = '147'

print('=>PYTHONTEX:STDOUT#14#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#14#i#\n')
pytex.before()
print(pytex.formatter(P))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '15'
pytex.line = '148'

print('=>PYTHONTEX:STDOUT#15#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#15#i#\n')
pytex.before()
print(pytex.formatter(P))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '16'
pytex.line = '148'

print('=>PYTHONTEX:STDOUT#16#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#16#i#\n')
pytex.before()
print(pytex.formatter(A**-_sage_const_1 ))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '17'
pytex.line = '176'

print('=>PYTHONTEX:STDOUT#17#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#17#block#\n')
pytex.before()
A = matrix(QQ, [ [_sage_const_3 , _sage_const_2 , -_sage_const_1 ], [-_sage_const_1 , _sage_const_1 , _sage_const_2 ], [_sage_const_1 , _sage_const_4 , _sage_const_3 ] ])
P = QQ['a']; (a,) = P._first_ngens(1)
B = matrix(P, [[_sage_const_3 ], [_sage_const_1 ], [_sage_const_2 *a+_sage_const_1 ]])
AB = block_matrix([ [A, B] ])
C = AB.echelon_form()
C1 = C(a=_sage_const_2 )
C2 = C1.echelon_form()
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '18'
pytex.line = '188'

print('=>PYTHONTEX:STDOUT#18#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#18#i#\n')
pytex.before()
print(pytex.formatter(AB))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '19'
pytex.line = '188'

print('=>PYTHONTEX:STDOUT#19#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#19#i#\n')
pytex.before()
print(pytex.formatter(C))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '20'
pytex.line = '190'

print('=>PYTHONTEX:STDOUT#20#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#20#i#\n')
pytex.before()
print(pytex.formatter(C1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '21'
pytex.line = '190'

print('=>PYTHONTEX:STDOUT#21#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#21#i#\n')
pytex.before()
print(pytex.formatter(C2))
pytex.after()


pytex.cleanup()

