# -*- coding: UTF-8 -*-


# This file was *autogenerated* from the file pythontex-files-tarea04/sage_default_default.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3)


import os
import sys
import codecs

if '--interactive' not in sys.argv[_sage_const_1 :]:
    if sys.version_info[_sage_const_0 ] == _sage_const_2 :
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr, 'strict')
    else:
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer, 'strict')

if '/usr/share/texlive/texmf-dist/scripts/pythontex' and '/usr/share/texlive/texmf-dist/scripts/pythontex' not in sys.path:
    sys.path.append('/usr/share/texlive/texmf-dist/scripts/pythontex')
from pythontex_utils import PythonTeXUtils
pytex = PythonTeXUtils()

pytex.docdir = os.getcwd()
if os.path.isdir('.'):
    os.chdir('.')
    if os.getcwd() not in sys.path:
        sys.path.append(os.getcwd())
else:
    if len(sys.argv) < _sage_const_2  or sys.argv[_sage_const_1 ] != '--manual':
        sys.exit('Cannot find directory .')
if pytex.docdir not in sys.path:
    sys.path.append(pytex.docdir)

pytex.formatter = latex


pytex.id = 'sage_default_default'
pytex.family = 'sage'
pytex.session = 'default'
pytex.restart = 'default'

pytex.command = 'code'
pytex.set_context('')
pytex.args = ''
pytex.instance = '0'
pytex.line = '18'

print('=>PYTHONTEX:STDOUT#0#code#')
sys.stderr.write('=>PYTHONTEX:STDERR#0#code#\n')
pytex.before()
B = matrix(QQ,[[_sage_const_4 ,-_sage_const_1 ,_sage_const_2 ],
[_sage_const_1 ,-_sage_const_1 ,-_sage_const_2 ],
[_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ],
[-_sage_const_1 ,_sage_const_0 ,-_sage_const_2 ],
[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '1'
pytex.line = '26'

print('=>PYTHONTEX:STDOUT#1#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#1#i#\n')
pytex.before()
print(pytex.formatter(B))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '2'
pytex.line = '42'

print('=>PYTHONTEX:STDOUT#2#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#2#block#\n')
pytex.before()
B = matrix(QQ,[[_sage_const_4 ,-_sage_const_1 ,_sage_const_2 ],[_sage_const_1 ,-_sage_const_1 ,-_sage_const_2 ],[_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ],[-_sage_const_1 ,_sage_const_0 ,-_sage_const_2 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]])
B1 = block_matrix([[B,_sage_const_1 ]])
B1R = B1.echelon_form()
B1R2 = copy(B1R)
B1R2.subdivide(_sage_const_3 ,_sage_const_3 )
A = B1R2.subdivision(_sage_const_0 ,_sage_const_1 )
H = B1R2.subdivision(_sage_const_1 ,_sage_const_1 )
Pol = QQ['a1, a2, b1, b2, c1, c2']; (a1, a2, b1, b2, c1, c2,) = Pol._first_ngens(6)
C = matrix(Pol,[[a1,a2],[b1,b2],[c1,c2]])
Sol = A + C*H

D = Sol[_sage_const_0 ,:]
E = matrix(QQ, [[_sage_const_1 , _sage_const_1 , -_sage_const_2 , _sage_const_0 , _sage_const_0 ]])
a1 = _sage_const_1 
a2 = _sage_const_1 
F = matrix(Pol,[[a1,a2],[b1,b2],[c1,c2]])
Sol2 = A + F*H
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '3'
pytex.line = '62'

print('=>PYTHONTEX:STDOUT#3#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#3#i#\n')
pytex.before()
print(pytex.formatter(B1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '4'
pytex.line = '62'

print('=>PYTHONTEX:STDOUT#4#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#4#i#\n')
pytex.before()
print(pytex.formatter(B1R))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '5'
pytex.line = '68'

print('=>PYTHONTEX:STDOUT#5#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#5#i#\n')
pytex.before()
print(pytex.formatter(B1R2))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '6'
pytex.line = '69'

print('=>PYTHONTEX:STDOUT#6#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#6#i#\n')
pytex.before()
print(pytex.formatter(A))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '7'
pytex.line = '70'

print('=>PYTHONTEX:STDOUT#7#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#7#i#\n')
pytex.before()
print(pytex.formatter(H))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '8'
pytex.line = '73'

print('=>PYTHONTEX:STDOUT#8#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#8#i#\n')
pytex.before()
print(pytex.formatter(A))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '9'
pytex.line = '73'

print('=>PYTHONTEX:STDOUT#9#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#9#i#\n')
pytex.before()
print(pytex.formatter(B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '10'
pytex.line = '73'

print('=>PYTHONTEX:STDOUT#10#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#10#i#\n')
pytex.before()
print(pytex.formatter(A*B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '11'
pytex.line = '74'

print('=>PYTHONTEX:STDOUT#11#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#11#i#\n')
pytex.before()
print(pytex.formatter(H))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '12'
pytex.line = '74'

print('=>PYTHONTEX:STDOUT#12#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#12#i#\n')
pytex.before()
print(pytex.formatter(B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '13'
pytex.line = '74'

print('=>PYTHONTEX:STDOUT#13#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#13#i#\n')
pytex.before()
print(pytex.formatter(H*B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '14'
pytex.line = '82'

print('=>PYTHONTEX:STDOUT#14#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#14#i#\n')
pytex.before()
print(pytex.formatter(A))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '15'
pytex.line = '82'

print('=>PYTHONTEX:STDOUT#15#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#15#i#\n')
pytex.before()
print(pytex.formatter(C))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '16'
pytex.line = '82'

print('=>PYTHONTEX:STDOUT#16#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#16#i#\n')
pytex.before()
print(pytex.formatter(H))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '17'
pytex.line = '83'

print('=>PYTHONTEX:STDOUT#17#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#17#i#\n')
pytex.before()
print(pytex.formatter(Sol))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '18'
pytex.line = '90'

print('=>PYTHONTEX:STDOUT#18#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#18#i#\n')
pytex.before()
print(pytex.formatter(D))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '19'
pytex.line = '93'

print('=>PYTHONTEX:STDOUT#19#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#19#i#\n')
pytex.before()
print(pytex.formatter(E))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '20'
pytex.line = '103'

print('=>PYTHONTEX:STDOUT#20#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#20#i#\n')
pytex.before()
print(pytex.formatter(Sol2))
pytex.after()


pytex.cleanup()

