# -*- coding: UTF-8 -*-


# This file was *autogenerated* from the file pythontex-files-Tarea09/sage_default_default.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p9791609077659043 = RealNumber('0.9791609077659043'); _sage_const_0p430715356970999 = RealNumber('0.430715356970999'); _sage_const_1p5250083079649113 = RealNumber('1.5250083079649113'); _sage_const_0p061165657369748695 = RealNumber('0.061165657369748695'); _sage_const_2p7989027102112827 = RealNumber('2.7989027102112827'); _sage_const_0p5015548718775755 = RealNumber('0.5015548718775755'); _sage_const_1p912158417289881 = RealNumber('1.912158417289881'); _sage_const_0p24440901271557722 = RealNumber('0.24440901271557722'); _sage_const_0p8205530309864537 = RealNumber('0.8205530309864537'); _sage_const_0p42261180235811696 = RealNumber('0.42261180235811696'); _sage_const_1p914008178794904 = RealNumber('1.914008178794904'); _sage_const_0p17482280182386326 = RealNumber('0.17482280182386326'); _sage_const_3p0850261801730925 = RealNumber('3.0850261801730925'); _sage_const_1p0104522969296543 = RealNumber('1.0104522969296543'); _sage_const_0p15356067616723457 = RealNumber('0.15356067616723457'); _sage_const_1p7711019287922931 = RealNumber('1.7711019287922931'); _sage_const_2p0952887890653016 = RealNumber('2.0952887890653016'); _sage_const_0p03975209722972092 = RealNumber('0.03975209722972092'); _sage_const_2p514022662217597 = RealNumber('2.514022662217597'); _sage_const_0p6049726172196987 = RealNumber('0.6049726172196987'); _sage_const_p2 = RealNumber('.2')


import os
import sys
import codecs

if '--interactive' not in sys.argv[_sage_const_1 :]:
    if sys.version_info[_sage_const_0 ] == _sage_const_2 :
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr, 'strict')
    else:
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer, 'strict')
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer, 'strict')

if '/usr/share/texlive/texmf-dist/scripts/pythontex' and '/usr/share/texlive/texmf-dist/scripts/pythontex' not in sys.path:
    sys.path.append('/usr/share/texlive/texmf-dist/scripts/pythontex')
from pythontex_utils import PythonTeXUtils
pytex = PythonTeXUtils()

pytex.docdir = os.getcwd()
if os.path.isdir('.'):
    os.chdir('.')
    if os.getcwd() not in sys.path:
        sys.path.append(os.getcwd())
else:
    if len(sys.argv) < _sage_const_2  or sys.argv[_sage_const_1 ] != '--manual':
        sys.exit('Cannot find directory .')
if pytex.docdir not in sys.path:
    sys.path.append(pytex.docdir)

pytex.formatter = latex


pytex.id = 'sage_default_default'
pytex.family = 'sage'
pytex.session = 'default'
pytex.restart = 'default'

pytex.command = 'code'
pytex.set_context('')
pytex.args = ''
pytex.instance = '0'
pytex.line = '30'

print('=>PYTHONTEX:STDOUT#0#code#')
sys.stderr.write('=>PYTHONTEX:STDERR#0#code#\n')
pytex.before()
latex.matrix_delimiters("[", "]")
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '1'
pytex.line = '41'

print('=>PYTHONTEX:STDOUT#1#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#1#sub#\n')
pytex.before()
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '2'
pytex.line = '66'

print('=>PYTHONTEX:STDOUT#2#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#2#block#\n')
pytex.before()
r1=vector(RR,[_sage_const_2 ,_sage_const_2 ,-_sage_const_1 ])
r2=vector(RR,[_sage_const_1 ,-_sage_const_1 ,_sage_const_3 ])
v1 = r1.cross_product(r2)
v2 = r1
v3 = v1.cross_product(v2)
u1 = v1/v1.norm()
u2 = v2/v2.norm()
u3 = v3/v3.norm()
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '3'
pytex.line = '81'

print('=>PYTHONTEX:STDOUT#3#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#3#i#\n')
pytex.before()
print(pytex.formatter(det(matrix([u1,u2,u3]))))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '4'
pytex.line = '84'

print('=>PYTHONTEX:STDOUT#4#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#4#block#\n')
pytex.before()
A = -_sage_const_2 *u2 + -_sage_const_2 *u3
B = -_sage_const_2 *u2 + +_sage_const_2 *u3
C = +_sage_const_2 *u2 + +_sage_const_2 *u3
D = +_sage_const_2 *u2 + -_sage_const_2 *u3
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '5'
pytex.line = '93'

print('=>PYTHONTEX:STDOUT#5#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#5#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_1p2 *u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_1p2 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_1p2 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(A)
print('=>PYTHONTEX:FIELD_DELIM#')
print(B)
print('=>PYTHONTEX:FIELD_DELIM#')
print(C)
print('=>PYTHONTEX:FIELD_DELIM#')
print(D)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '6'
pytex.line = '114'

print('=>PYTHONTEX:STDOUT#6#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#6#block#\n')
pytex.before()
v1=vector(RR,[_sage_const_2 ,_sage_const_0 ,-_sage_const_1 ])
v2=vector(RR,[_sage_const_0 ,_sage_const_2 ,_sage_const_0 ])
v3 = v1.cross_product(v2)
u1 = v1/v1.norm()
u2 = v2/v2.norm()
u3 = v3/v3.norm()
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '7'
pytex.line = '125'

print('=>PYTHONTEX:STDOUT#7#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#7#i#\n')
pytex.before()
print(pytex.formatter(det(matrix([u1,u2,u3]))))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '8'
pytex.line = '128'

print('=>PYTHONTEX:STDOUT#8#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#8#block#\n')
pytex.before()
A = -_sage_const_2 *u2 + -_sage_const_2 *u3
B = -_sage_const_2 *u2 + +_sage_const_2 *u3
C = +_sage_const_2 *u2 + +_sage_const_2 *u3
D = +_sage_const_2 *u2 + -_sage_const_2 *u3
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '9'
pytex.line = '137'

print('=>PYTHONTEX:STDOUT#9#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#9#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_1p2 *u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_1p2 *u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(_sage_const_1p2 *u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(u1)
print('=>PYTHONTEX:FIELD_DELIM#')
print(u2)
print('=>PYTHONTEX:FIELD_DELIM#')
print(u3)
print('=>PYTHONTEX:FIELD_DELIM#')
print(A)
print('=>PYTHONTEX:FIELD_DELIM#')
print(B)
print('=>PYTHONTEX:FIELD_DELIM#')
print(C)
print('=>PYTHONTEX:FIELD_DELIM#')
print(D)
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '10'
pytex.line = '162'

print('=>PYTHONTEX:STDOUT#10#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#10#block#\n')
pytex.before()
H=matrix(QQ,[[-_sage_const_1 ,-_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_2 ],[_sage_const_2 ,_sage_const_0 ,_sage_const_1 ,_sage_const_1 ,_sage_const_0 ]])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '11'
pytex.line = '165'

print('=>PYTHONTEX:STDOUT#11#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#11#i#\n')
pytex.before()
print(pytex.formatter(H))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '12'
pytex.line = '175'

print('=>PYTHONTEX:STDOUT#12#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#12#block#\n')
pytex.before()
H=matrix(QQ,[[-_sage_const_1 ,-_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_2 ],[_sage_const_2 ,_sage_const_0 ,_sage_const_1 ,_sage_const_1 ,_sage_const_0 ]])
HT1 = block_matrix([[H.T,_sage_const_1 ]])
HT1R = copy(HT1.echelon_form())
HT1R.subdivide(_sage_const_2 ,_sage_const_2 )
B = HT1R.subdivision(_sage_const_1 ,_sage_const_1 ).T
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '13'
pytex.line = '181'

print('=>PYTHONTEX:STDOUT#13#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#13#i#\n')
pytex.before()
print(pytex.formatter(HT1))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '14'
pytex.line = '181'

print('=>PYTHONTEX:STDOUT#14#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#14#i#\n')
pytex.before()
print(pytex.formatter(HT1R))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '15'
pytex.line = '185'

print('=>PYTHONTEX:STDOUT#15#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#15#i#\n')
pytex.before()
print(pytex.formatter(B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '16'
pytex.line = '185'

print('=>PYTHONTEX:STDOUT#16#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#16#i#\n')
pytex.before()
print(pytex.formatter(B.echelon_form()))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '17'
pytex.line = '188'

print('=>PYTHONTEX:STDOUT#17#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#17#i#\n')
pytex.before()
print(pytex.formatter(matrix([B.column(_sage_const_0 )]).T))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '18'
pytex.line = '188'

print('=>PYTHONTEX:STDOUT#18#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#18#i#\n')
pytex.before()
print(pytex.formatter(matrix([B.column(_sage_const_1 )]).T))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '19'
pytex.line = '188'

print('=>PYTHONTEX:STDOUT#19#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#19#i#\n')
pytex.before()
print(pytex.formatter(matrix([B.column(_sage_const_2 )]).T))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '20'
pytex.line = '191'

print('=>PYTHONTEX:STDOUT#20#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#20#block#\n')
pytex.before()
v1 = B.column(_sage_const_0 )
v2 = B.column(_sage_const_1 )
v3 = B.column(_sage_const_2 )
w1 = v1
w2 = v2 - ((v2*w1)/(w1*w1)) * w1
w3 = v3 - ((v3*w2)/(w2*w2)) * w2 - ((v3*w1)/(w1*w1)) * w1
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '21'
pytex.line = '199'

print('=>PYTHONTEX:STDOUT#21#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#21#i#\n')
pytex.before()
print(pytex.formatter(matrix([B.column(_sage_const_0 )]).T))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '22'
pytex.line = '200'

print('=>PYTHONTEX:STDOUT#22#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#22#i#\n')
pytex.before()
print(pytex.formatter(matrix([w2]).T))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '23'
pytex.line = '201'

print('=>PYTHONTEX:STDOUT#23#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#23#i#\n')
pytex.before()
print(pytex.formatter(matrix([w3]).T))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '24'
pytex.line = '205'

print('=>PYTHONTEX:STDOUT#24#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#24#block#\n')
pytex.before()
u1 = w1/w1.norm()
u2 = w2/w2.norm()
u3 = w3/w3.norm()
B2 = column_matrix([u1,u2,u3])
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '25'
pytex.line = '215'

print('=>PYTHONTEX:STDOUT#25#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#25#i#\n')
pytex.before()
print(pytex.formatter(B2))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '26'
pytex.line = '215'

print('=>PYTHONTEX:STDOUT#26#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#26#i#\n')
pytex.before()
print(pytex.formatter(B2.echelon_form()))
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '27'
pytex.line = '222'

print('=>PYTHONTEX:STDOUT#27#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#27#block#\n')
pytex.before()
XY = matrix(RR,[[ _sage_const_0p9791609077659043  ,  -_sage_const_0p430715356970999  ],
                [ _sage_const_1p5250083079649113  ,  _sage_const_0p061165657369748695  ],
                [ _sage_const_2p7989027102112827  ,  -_sage_const_0p5015548718775755  ],
                [ _sage_const_1p912158417289881  ,  _sage_const_0p24440901271557722  ],
                [ _sage_const_0p8205530309864537  ,  -_sage_const_0p42261180235811696  ],
                [ _sage_const_1p914008178794904  ,  -_sage_const_0p17482280182386326  ],
                [ _sage_const_3p0850261801730925  ,  -_sage_const_1p0104522969296543  ],
                [ _sage_const_0p15356067616723457  ,  -_sage_const_1p7711019287922931  ],
                [ _sage_const_2p0952887890653016  ,  _sage_const_0p03975209722972092  ],
                [ _sage_const_2p514022662217597  ,  -_sage_const_0p6049726172196987  ]])

X = XY.column(_sage_const_0 )
Y = XY.column(_sage_const_1 )
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '28'
pytex.line = '240'

print('=>PYTHONTEX:STDOUT#28#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#28#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(set(XY.rows()))
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(X)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(X)+_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(Y)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(Y)+_sage_const_2 )
pytex.after()
pytex.command = 'block'
pytex.set_context('')
pytex.args = ''
pytex.instance = '29'
pytex.line = '257'

print('=>PYTHONTEX:STDOUT#29#block#')
sys.stderr.write('=>PYTHONTEX:STDERR#29#block#\n')
pytex.before()
B = matrix([[_sage_const_1  for x in X],
          [x for x in X],
          [x**_sage_const_2  for x in X]]).T
C = (B.T*B)**-_sage_const_1 *B.T*Y
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '30'
pytex.line = '264'

print('=>PYTHONTEX:STDOUT#30#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#30#i#\n')
pytex.before()
print(pytex.formatter(B))
pytex.after()
pytex.command = 'i'
pytex.set_context('')
pytex.args = ''
pytex.instance = '31'
pytex.line = '267'

print('=>PYTHONTEX:STDOUT#31#i#')
sys.stderr.write('=>PYTHONTEX:STDERR#31#i#\n')
pytex.before()
print(pytex.formatter(C))
pytex.after()
pytex.command = 'sub'
pytex.set_context('')
pytex.args = ''
pytex.instance = '32'
pytex.line = '272'

print('=>PYTHONTEX:STDOUT#32#sub#')
sys.stderr.write('=>PYTHONTEX:STDERR#32#sub#\n')
pytex.before()
print('=>PYTHONTEX:FIELD_DELIM#')
print(set(XY.rows()))
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(X)-_sage_const_p2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(X)+_sage_const_p2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_0 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_1 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(C[_sage_const_2 ])
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(X)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(X)+_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(min(Y)-_sage_const_2 )
print('=>PYTHONTEX:FIELD_DELIM#')
print(max(Y)+_sage_const_2 )
pytex.after()


pytex.cleanup()

